### ISSUE TITLE
500 Error as response of the API

### ISSUE THREAD

**Issue by tomjpeg** [salmannotkhan/Fiverr-API#1]
First of all, thank you for the small API. 

Partially, this also works for me without any problems. But after 1-2 successful requests I always get back "Internal Server Error" as API response.  No matter if in your Vercel instance or self-hosted in a Docker container in both I get the same error.

![image](https://user-images.githubusercontent.com/75305857/137019922-1fd1e458-1551-4c32-8b63-ccf7dbe84cfc.png)

Is it possible that Fiverr blocks the IP after 1-2 requests? What are your experiences there? 

I also created a simple dockerfile to push the API quickly and easily, maybe that would be something for the repo. 

Thanks again for the project.

**Comment by slmnsh** [comment]
Hello Tom,

I tested this but haven't faced any Error 500. Can you elaborate how to reproduce this issue?(e.g. username and endpoint)

Also, Properly implemented docker would be a nice addon. Make a PR and make sure the code is clean because I believe that dirty code is worse than buggy code :)

**Comment by tomjpeg** [comment]
Hello Salman,
thank you for your quick reply.

Your point with the username made me test different usernames. I noticed that it comes to the errors as soon as you have queried a user with many reviews. 

For me it is about the user "leaherbeck". 

It's best to make 2-3 requests with this user and see if you get the error.

Thank you!

**Comment by slmnsh** [comment]
Ok gotcha. I'll try to solve error as soon as possible

**Comment by tomjpeg** [comment]
Perfect, thank you.

Do you have any idea what is causing the error?

**Comment by slmnsh** [comment]
Yeah, thing is the api(Fiverr's internal) I'm using to fetch the reviews fetches 5-10 reviews at a time.

So in order to fetch all reviews at once I have to make multiple requests

So when user makes single request to reviews endpoint. The server internally makes 4-5 requests(acoording to total number of reviews) to the Fiverr servers. And now if you want to make same request again it repeats the same process again and Fiverr rate limits the server.

**Comment by slmnsh** [comment]
I'm thinking that I'll limit the result returned by the api. So it'll reduce the number of requests to Fiverr server

**Comment by tomjpeg** [comment]
Yes, I already thought something like that. Everything else makes no sense. Do you have a quick fix ready or know when you will push it?

**Comment by slmnsh** [comment]
It'll take sometime maybe I'll do it in day or two.

**Comment by tomjpeg** [comment]
Thank you again!

**Comment by tomjpeg** [comment]
Anything new here? @salmannotkhan

**Comment by slmnsh** [comment]
> Anything new here? @salmannotkhan 

I forgot that I already have limit parameter in api. So you can use that and it won't make too many requests to the server
