### ISSUE TITLE
It seem not working

### ISSUE THREAD

**Issue by south1907** [salmannotkhan/Fiverr-API#2]
Hi [Salman Shaikh](https://github.com/salmannotkhan)

I try your project, but it seem not run.
I try `https://fiverr-api.vercel.app/`
and it return:
`{
  "error": {
    "code": "500",
    "message": "A server error has occurred"
  }
}`

**Comment by slmnsh** [comment]
The API seems to be working when tested locally there is some kind of issue
where it's not working after deployment. I can't figure out what is it.

**Comment by south1907** [comment]
I try run in on local, but It not run successful, same error

**Comment by slmnsh** [comment]
![image](https://user-images.githubusercontent.com/26996284/175347895-1486d56b-ef82-41eb-9b26-d04c3d81a83e.png)

**Comment by slmnsh** [comment]
Here it's still working fine

**Comment by south1907** [comment]
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/24355759/175349155-d502de13-9d2d-4f96-9d71-d2b9d6398e90.png">

when I run

**Comment by slmnsh** [comment]
Yes I'm testing on other computer right now.

**Comment by slmnsh** [comment]
It's really strange that it works on my laptop only

**Comment by south1907** [comment]
It seem Fiverr detect it is not Human, but your laptop is exception :D
