### ISSUE TITLE
Serving locally with uvicorn fails

### ISSUE THREAD

**Issue by stoyan-scava** [salmannotkhan/Fiverr-API#3]
$ python3 -m uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [19039] using statreload
ERROR:    Error loading ASGI app. Could not import module "main".
CINFO:     Stopping reloader process [19039]

$ python3 -m uvicorn --version
Running uvicorn 0.14.0 with CPython 3.8.10 on Linux

**Comment by slmnsh** [comment]
It's actually

python3 -m uvicorn src.main:app --reload

**Comment by slmnsh** [comment]
Closing this issue as it's solved already
